// REQUIRE EXPRESS
// CREATE AN INSTANCE OF EXPRESS
// CREATE A PORT FOR THE APP TO RUN
// BUT ALSO LISTEN TO ENVIRONMENT VARIABLES SO WE CAN DEPLOY TO HEROKU
// ADD MIDDLEWARE
// COPY/PASTE FROM STAR WARS APP
// CREATE AN ARRAY OF TABLES
// CREATE AN ARRAY FOR WAITLIST
// ARRAYS OF OBJECTS. OBJECTS SHOULD HAVE
// NAME
// PHONE
// EMAIL
// ID
// HTML ROUTES
// ROUTE FOR HOME
// ROUTE FOR TABLES
// ROUTE FOR RESERVE
// API ROUTES
// GET ALL TABLE DATA
// CREATE A TABLE/RESERVATION
// LISTEN ON THE PORT